language: python
group: travis_latest
cache: pip
python:
  - '3.6'

branches:
  only:
    - master
    - develop

os:
  linux

env:
  global:
  - secure: QM4CHEqPdDEUhrQYvkOz4DqxNjUNHLVRkxCSy4raFgTEAUyiPF+nF2z8Q1s8lfTxBwmjgEgLpxBMCRI2wbkLJirHwAdpvkH3aNzla4o2mgNdSyl1zSQrflM8/eJ3uEQjx69dcfPQWmED1hQQceh+Gd2c9hhfDdPv12viqHhFp5/TEeXRILHczbE0bC8efxSI87xi5a6rCm6c+Uohmc7Xy5+PraVsuxrRWU7NESqTYuIr14gT8p38SvwCafALpYw7i0Ch1ue/ffrsPKlnnCGd/HTE7YMcw61dUh9Y8QYTSJaBBdLS8ytwTyaN4/4LEEqaHihwKko8j03hUi+TM+d/lmKYh3y3U7U3BaofW/aGJu5Xuo6eKtgwA2WX/yTLdVQbnMgDOtJiKQ7G4wAKO4UUffRbdUc3ioOKBPEPjhyQ/Qo3NEozGt0SUNzEdeFIMaQbBQzxzGy+NNByPnOlvPK4u6hvAluPPVqGaVV7gAh5NRzPrAoChK2TYASZVCd9SQ8HfnFdv5aWn/rt6wnf2wVRcCxtQXSKdazaLFv1noSO44PWprRNskI2xYEjrFRMk/Drk7uNBCcJH0apBbDyAzaQ+izjyWllGztrebjQcJSagfhES/Rt6WBjuwAVzElHwRgIWxrGn1t0MzT3q7IfAQlXedRhGyv4e+dxehjZdv7m4W8=
  - SPHINX_DIR=doc/
  - HTML_DIR=doc/build/html
  - PYTHON_VERSION=3.6
  - CONDA_DEPENDENCIES="jupyter_contrib_nbextensions nglview sphinx ipywidgets matplotlib==3.2.2 MDAnalysis MDAnalysisTests plotly"
  - CONDA_CHANNELS='defaults conda-forge plotly'
  - PIP_DEPENDENCIES="sphinx_rtd_theme sphinx-sitemap nbsphinx ipython tabulate sphinxcontrib-bibtex pybtex msmb_theme==1.2.0"
  - CYTHON_TRACE_NOGIL=1
  - MPLBACKEND=agg


before_install:
  - sudo apt-get update
  - sudo apt-get install -y pandoc


install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - jupyter-nbextension enable nglview --py --sys-prefix
  - conda list
  
script:
  - make -C ${SPHINX_DIR} html

after_success:
  - |
    if [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then
      python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
      export URL="https://userguide.mdanalysis.org/"
      export VERSION=$(python -c "import MDAnalysis; print(MDAnalysis.__version__)")
      export MAINTAIN_DIR=${TRAVIS_BUILD_DIR}/maintainer
      export MDA_DOCDIR=$HTML_DIR
      export GH_REPOSITORY=github.com/MDAnalysis/UserGuide.git
      export GIT_CI_USER=TravisCI
      export GIT_CI_EMAIL=TravisCI@mdanalysis.org
      export GH_DOC_BRANCH=$TRAVIS_BRANCH
      echo "Creating docs"
      bash ${MAINTAIN_DIR}/deploy_docs_via_travis.sh
    fi
