version: 2
sphinx:
  configuration: doc/source/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-4.10"

conda:
  environment: environment.yml
formats:
- epub
- pdf
- htmlzip
